# Generated by Django 6.0.3 on 2026-03-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='books-images/Atomic-Habits.png', upload_to='books-images/'),
        ),
    ]
